version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      - APP_ENV=${APP_ENV}
    command: >
      bash -c "
      chown -R www-data:www-data storage bootstrap/cache &&
      php artisan config:clear &&
      php artisan route:clear &&
      php artisan key:generate &&
      /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"

volumes:
  vendor: