version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: >
      bash -c "
      chown -R www-data:www-data storage bootstrap/cache &&
      php artisan config:clear &&
      php artisan route:clear &&
      php artisan key:generate"
  
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  vendor: