version: '3.8'

services:
  app:
    build: ./docker/php
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mongo
  
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
